### ISSUE TITLE
i use the brach 20160728_immigrate_to_ocr raise error

### ISSUE THREAD

**Issue by LinJM** [synckey/tensorflow_lstm_ctc_ocr#2]
Invalid argument: Saw a non-null label (index >= num_classes - 1) following a null label, batch: 0 num_classes: 12 labels: 2,10,5,1

**Comment by xisnu** [comment]
I got the same error too. Have no idea how tensorflow is processing the labels.

**Comment by xisnu** [comment]
@LinJM can you give one sample of your target label and how you have used <blank>

**Comment by synckey** [comment]
@xisnu @LinJM I have added the readme to the master branch, you can read it. Sorry for responding late, for I don't have stable access to gmail in China.
