### ISSUE TITLE
Why in the test part will appear (test and detect length doesn't match) error

### ISSUE THREAD

**Issue by LinJM** [synckey/tensorflow_lstm_ctc_ocr#3]
hi, @synckey , I run your great program, but I will raise an error like this:

test and detect length desn't match

I was confused.

The actually code is in the lstm_and_ctc_ocr_train.py  function report_accuracy()。

**Comment by synckey** [comment]
Initially,the model is not strong enough to recognise every test example.After some steps it will be able to predict all the test examples. So, you can just ignore this error for the first few  iterations.

**Comment by wanghaisheng** [comment]
how to generate testing and training data @synckey @LinJM

**Comment by wanghaisheng** [comment]
how to generate testing and training data @synckey @LinJM

**Comment by wanghaisheng** [comment]
@synckey  there is 
SUN397 Scene benchmark (397 scene categories), tar file (37GB, md5sum=58b3a6f1b8d6ec003458f940ada226bb) and project page for code, precomputed features, etc.
SUN2012: 16,873 images, tar file (7.3GB).

which one

**Comment by technologistkj** [comment]
Hi Team, which imageset should we download from Sun Database ?

**Comment by technologistkj** [comment]
None of the image folders in the 7.5 GB dataset has naming format of {:08d}.jpg

**Comment by auroralinan** [comment]
@synckey It seems none of the folders in SUN2012 contains bgs folder. Would you please give more information?

**Comment by synckey** [comment]
@auroralinan @technologistkj @wanghaisheng  I've add the readme  to show how to generate the train and test data.

**Comment by technologistkj** [comment]
Thanks you Andy..
